# Generated by Django 5.1.4 on 2025-01-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseupload', '0002_coursesection_semester_year_alter_course_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresponse',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='facultyresponse',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='courseresponse',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responseupload.year'),
        ),
        migrations.AddField(
            model_name='facultyresponse',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responseupload.year'),
        ),
    ]
