# Generated by Django 5.1.4 on 2025-01-03 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseupload', '0003_remove_courseresponse_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategory',
            new_name='Role',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_category',
        ),
        migrations.AddField(
            model_name='courseresponse',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='responseupload.role'),
        ),
        migrations.AddField(
            model_name='facultyresponse',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
