# Generated by Django 5.1.4 on 2025-04-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseupload', '0005_remove_customuser_groups_remove_customuser_roles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'year', 'semester'], 'verbose_name': 'Course Definition', 'verbose_name_plural': 'Course Definitions'},
        ),
        migrations.AlterModelOptions(
            name='courseresponse',
            options={'ordering': ['-uploaded_at', 'course', 'faculty'], 'verbose_name': 'Course Evaluation Response', 'verbose_name_plural': 'Course Evaluation Responses'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty (Legacy Info)', 'verbose_name_plural': 'Faculty (Legacy Info)'},
        ),
        migrations.AlterModelOptions(
            name='facultyresponse',
            options={'ordering': ['-uploaded_at', 'course', 'faculty'], 'verbose_name': 'Faculty Evaluation Response', 'verbose_name_plural': 'Faculty Evaluation Responses'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['name'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-name'], 'verbose_name': 'Year', 'verbose_name_plural': 'Years'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'program', 'semester', 'year')},
        ),
        migrations.AddField(
            model_name='courseresponse',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyresponse',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Standard course code (e.g., CSE110).', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Full title of the course.', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(help_text='The program this course belongs to.', on_delete=django.db.models.deletion.CASCADE, to='responseupload.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(help_text='The semester this course definition is primarily associated with (e.g., catalog semester).', on_delete=django.db.models.deletion.CASCADE, to='responseupload.semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(help_text='The academic year this course definition is primarily associated with (e.g., catalog year).', on_delete=django.db.models.deletion.CASCADE, to='responseupload.year'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='The faculty member associated with this course evaluation (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='q1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1. Learning/Competencies'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='q2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2. Textbooks/Materials'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='q3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3. Time Allocation'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='q4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='4. Syllabus Coverage'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.semester'),
        ),
        migrations.AlterField(
            model_name='courseresponse',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.year'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='The faculty member being evaluated.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1. Organization'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2. Clarity'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3. Teaching Methods'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='4. Learning Materials'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='5. Engagement Effort'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='6. Encouragement'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='7. Assignment Guidance'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='q8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='8. Time Management'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.semester'),
        ),
        migrations.AlterField(
            model_name='facultyresponse',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.year'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(help_text='Short unique code for the program.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Full name of the program.', max_length=200),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='Name of the semester (e.g., Spring, Summer, Fall).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(help_text='Academic year (e.g., 2024).', unique=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
