# Generated by Django 5.1.4 on 2025-04-21 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0003_alter_courseassignment_options_and_more'),
        ('responseupload', '0005_remove_customuser_groups_remove_customuser_roles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='modality',
            field=models.CharField(choices=[('online', 'Online'), ('f2f', 'Face-to-Face'), ('blended', 'Blended')], default='online', help_text='The primary delivery mode of the course.', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='num_classes',
            field=models.IntegerField(blank=True, help_text='Optional: Total number of classes scheduled.', null=True),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='zoom_link',
            field=models.URLField(blank=True, help_text='Zoom meeting link (if applicable).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='course_assignment',
            field=models.ForeignKey(help_text='The course assignment this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='f2f_sessions', to='managerpanel.courseassignment'),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='date',
            field=models.DateField(help_text='Date of the session.'),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='it_support_name',
            field=models.CharField(blank=True, help_text='IT support contact (optional).', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='it_support_number',
            field=models.CharField(blank=True, help_text='IT support contact number (optional).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='location',
            field=models.CharField(help_text='Building or general location.', max_length=200),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='support_staff_name',
            field=models.CharField(blank=True, help_text='Support staff present (optional).', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='time',
            field=models.TimeField(help_text='Time of the session.'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to the built-in User model.', on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the batch (e.g., 'Spring 2024 CSE')", max_length=150, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Year the batch started/enrolled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(blank=True, help_text='Optional: Semester the batch started/enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.semester')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-year', 'semester__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this assignment to a specific student batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='managerpanel.batch'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student ID number.', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Unique student email address.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Student's contact phone number (optional).", max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Active'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', help_text='Current status of the student.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Any relevant notes about the student (optional).', null=True)),
                ('batch', models.ForeignKey(help_text='The batch this student belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='managerpanel.batch')),
                ('enrollment_semester', models.ForeignKey(blank=True, help_text='Semester the student originally enrolled (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responseupload.semester')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['batch', 'last_name', 'first_name'],
            },
        ),
    ]
