# Generated by Django 5.1.4 on 2025-04-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0004_alter_courseassignment_modality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_friday',
            field=models.BooleanField(default=False, verbose_name='Fri'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_monday',
            field=models.BooleanField(default=False, verbose_name='Mon'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_saturday',
            field=models.BooleanField(default=False, verbose_name='Sat'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_sunday',
            field=models.BooleanField(default=False, verbose_name='Sun'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_thursday',
            field=models.BooleanField(default=False, verbose_name='Thu'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_tuesday',
            field=models.BooleanField(default=False, verbose_name='Tue'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='meets_on_wednesday',
            field=models.BooleanField(default=False, verbose_name='Wed'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
