# Generated by Django 5.1.4 on 2025-04-22 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0005_courseassignment_meets_on_friday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cohort (e.g., TFB, Private, Scholarship Group A)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the cohort.', null=True)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'cohort__name', 'semester__name', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('pgd_med', 'P.Gd - M.ED'), ('pgd_ecd', 'P.Gd - ECD'), ('med', 'M.Ed'), ('ecd', 'ECD')], help_text="Student's degree program (optional).", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text="Unique name for the batch (e.g., 'Spring 2024 CSE - TFB')", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='is_manager',
            field=models.BooleanField(default=True, help_text='Designates whether this user has manager privileges.'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to the built-in User model.', on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='cohort',
            field=models.ForeignKey( null=True, help_text='The cohort this batch belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='managerpanel.cohort'),
            preserve_default=False,
        ),
    ]
