# Generated by Django 5.1.4 on 2025-04-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0006_cohort_alter_batch_options_student_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='cohort',
            field=models.ForeignKey(help_text='The cohort this batch belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='managerpanel.cohort'),
        ),
    ]
