# Generated by Django 5.1.4 on 2025-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0007_alter_batch_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='cohort',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'semester__name', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text="Unique name for the batch (e.g., 'Spring 2024 CSE')", max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
    ]
