# Generated by Django 5.1.4 on 2025-04-23 09:41
import django.db.models.deletion
from django.db import migrations, models

def create_default_cohort(apps, schema_editor):
    Cohort = apps.get_model('managerpanel', 'Cohort')
    # Create a default Cohort if it doesn't exist
    Cohort.objects.get_or_create(
        id=1,
        defaults={'name': 'Default Cohort', 'description': 'Default cohort for batches'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0008_remove_batch_cohort_alter_batch_options_and_more'),
        ('responseupload', '0001_initial'),  # Adjust to the correct responseupload migration
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cohort (e.g., TFB, Private, Scholarship Group A)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the cohort.', null=True)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_cohort, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'cohort__name', 'semester__name', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['batch__name', 'last_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text="Unique name for the batch (e.g., 'Spring 2024 CSE - TFB')", max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='cohort',
            field=models.ForeignKey(default=1, help_text='The cohort this batch belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='managerpanel.cohort'),
        ),
    ]