# Generated by Django 5.1.4 on 2025-04-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0009_cohort_alter_batch_options_alter_student_options_and_more'),
        ('responseupload', '0006_alter_course_options_alter_courseresponse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'semester__name', 'program__code', 'cohort__name', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(default=2, help_text='The academic program this batch is for.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='responseupload.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='cohort',
            field=models.ForeignKey(help_text='The cohort this batch belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='managerpanel.cohort'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='managerpanel.batch'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(help_text='The course being assigned.', on_delete=django.db.models.deletion.CASCADE, to='responseupload.course'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='end_date',
            field=models.DateField(help_text='End date.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='end_time',
            field=models.TimeField(help_text='Default end time.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='faculty_members',
            field=models.ManyToManyField(help_text='Assigned faculty.', limit_choices_to={'is_staff': False, 'is_superuser': False}, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='modality',
            field=models.CharField(choices=[('online', 'Online'), ('f2f', 'Face-to-Face'), ('blended', 'Blended')], default='online', help_text='Primary delivery mode.', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='num_classes',
            field=models.IntegerField(blank=True, help_text='Optional: Total classes.', null=True),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='start_date',
            field=models.DateField(help_text='Start date.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='start_time',
            field=models.TimeField(help_text='Default start time.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='zoom_host_code',
            field=models.CharField(blank=True, help_text='Zoom host code (optional).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='zoom_link',
            field=models.URLField(blank=True, help_text='Zoom link (optional).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='course_assignment',
            field=models.ForeignKey(help_text='Assignment this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='f2f_sessions', to='managerpanel.courseassignment'),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='date',
            field=models.DateField(help_text='Date of session.'),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='it_support_number',
            field=models.CharField(blank=True, help_text='IT support number (optional).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='location',
            field=models.CharField(help_text='Location.', max_length=200),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room (optional).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='support_staff_name',
            field=models.CharField(blank=True, help_text='Support staff (optional).', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facetofacesession',
            name='time',
            field=models.TimeField(help_text='Time of session.'),
        ),
    ]
