# Generated by Django 5.1.4 on 2025-04-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0010_alter_batch_options_batch_program_alter_batch_cohort_and_more'),
        ('responseupload', '0006_alter_course_options_alter_courseresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'ordering': ['-year__name', '-semester__name', '-start_date', 'course__code'], 'verbose_name': 'Course Assignment', 'verbose_name_plural': 'Course Assignments'},
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester this assignment is offered in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='responseupload.semester'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Year this assignment is offered in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='responseupload.year'),
        ),
    ]
