# Generated by Django 5.1.4 on 2025-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0011_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'status', 'semester__name', 'program__code', 'cohort__name', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ongoing', 'On-Going'), ('graduated', 'Graduated')], db_index=True, default='ongoing', help_text='Current status of the batch (e.g., On-Going, Graduated).', max_length=10),
        ),
    ]
