# Generated by Django 5.1.4 on 2025-04-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0012_alter_batch_options_batch_status'),
        ('responseupload', '0006_alter_course_options_alter_courseresponse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this student has successfully completed (independent of assignments).', related_name='completed_by_students', to='responseupload.course', verbose_name='Completed Courses'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='cohort',
            field=models.ForeignKey(help_text='The cohort this batch belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='managerpanel.cohort'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text='Unique name for the batch', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(help_text='The academic program this batch is for', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='responseupload.program'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ongoing', 'On-Going'), ('graduated', 'Graduated')], db_index=True, default='ongoing', help_text='Current status of the batch', max_length=10),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(help_text='Name of the cohort', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='is_manager',
            field=models.BooleanField(default=True, help_text='Designates manager privileges'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to User model', on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
